<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistFoodcriticLinter' => 'linters/ArcanistFoodcriticLinter.php',
    'ArcanistGoogleCppLinter' => 'linters/ArcanistGoogleCppLinter.php',
    'ArcanistScalastyleLinter' => 'linters/ArcanistScalastyleLinter.php',
    'SBTTestEngine' => 'unit/SBTTestEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistFoodcriticLinter' => 'ArcanistExternalLinter',
    'ArcanistGoogleCppLinter' => 'ArcanistExternalLinter',
    'ArcanistScalastyleLinter' => 'ArcanistExternalLinter',
    'SBTTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
